lib/controller.js
Fixes issue #3 
Changes: recursive call to github api
=> Display more than 100 repos

lib/controller.js, views/layouts/main.handlebars
Fixes issue #2 
Changes: Added Chart.js cdn and 2 functions.
One takes care of parsing the data-languages attribute in the div with id = chart-container to and object
and the other one creates the chart inside a canvas with that information
=> Add vertical graph that dinamically display programming language based on user's repos using Chart.js

lib/controller.js, views/layouts/main.handlebars
Fixes issue #5 
Changes: 
- added an array with messages for mystery language
- changed the null key to 'unknown'
=> Special behavior on `null` programming language

lib/controller.js, views/layouts/main.handlebars
Fixes issue #1 
Changes: beautified search bar & footer and added emojis based on no of repos
=> beautified search bar, footer & added emojis

.editorconfig, CONTRIBUTING.md, README.md, lib/controller.js, package.json
=> Minor updates

lib/controller.js, package-lock.json, package.json, views/layouts/main.handlebars
Fixes issue #18
Changes:
- Removed trailing comma in list of languages
- Hid chart for users that don't have repos
- Minor improvements of code structure in controller
=> Refactoring and chart hiding

.dockerignore, Dockerfile, README.md
Fixes issue #25
Changes: Added `.dockerignore` and `Dockerfile` and update README for instructions on using Docker. Used alpine as base image to produce a smaller size image.
=> Dockerize app

lib/public/css/screen.css, lib/public/js/chart.js, views/layouts/main.handlebars
=> Fix footer style

lib/public/css/screen.css
Fixes issue #28 Fix Footer Position
Changes: Simple bug fix in which whatever the footers size is, have the results div add on an extra 5% margin bottom.
=> Bug Fix #28 Fix Footer Position

CONTRIBUTING.md, lib/controller.js, package-lock.json
Changes: There was just always a space in before the exclamation point.
=> Bug Fix: Exclamation Point was always separated by a space.

README.md, lib/public/css/screen.css, lib/public/js/spinner.js, views/layouts/main.handlebars
Signed-off-by: Mohammed Azhar <azharakbar@gmail.com>
Fixes issue #15 
Changes: Displays A spinning loader till the API call returns with a response to the client browser.
=> Added Loading Animation During API-Fetch

.editorconfig, lib/app.js, lib/controller.js, views/layouts/main.handlebars, views/partials/404.handlebars, views/partials/body.handlebars, views/partials/head.handlebars
Separated the UI into different partials.
Handling 404 requests
=> Modularized the UI

lib/controller.js, lib/public/css/screen.css, lib/public/js/chart.js, views/layouts/main.handlebars
Fixes issue #33 
Changes: limited the number of languages in the chart to 20
=> Limit number of languages to 20

lib/public/css/screen.css
Fixes issue #44 
Changes:Overlap issue of the fork banner and footer padding
=> Fix Issue  #44

lib/public/js/chart.js
Issue: When toggle color and hovering on chart it become white #60 
Destroy chart on toggle color
=> Fix chart change into white color on hover

lib/public/css/screen.css, lib/public/js/chart.js, views/partials/body.handlebars
Fixes issue #64 
Changes: 
* two new css classes for active and inactive stages
* changes in body.handlebars (added button id)
* chart.js toggle function updated.
=> toggle button color change fix

lib/public/js/chart.js
=> saving the image with the .jpg extension and fix error message when Toggle color of Chart

views/partials/body.handlebars
In my opinion, the magnifying glass icon has explained that it is search button and its enrich the ux. #73
=> remove search word

package.json
Fixes issue #86 :
Steps : 
- `npm audit`
- `npm audit fix`
=> Update package.json (npm audit fix) #86

README.md
Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
=> Remove done checklist items

README.md, lib/app.js, package.json
=> Enable https

lib/public/css/screen/base.css, lib/public/js/chart.js
Fixes issue #101
Changes: in ```chart.js``` legend display was being shown conditionally causing to toggle the lang-stat label
Here's the working screencast:
=> fixed lang-stat not showing

lib/app.js, lib/controller.js, lib/error_messages.js
Fixes issue #112 
Changes: Add error_messages.js as dedicated file for error messages.
=> Refactor error codes

lib/public/js/chart.js
Fixes issue #121 
Changes: Add username in filename to be saved.
=> Name chart based on username

views/partials/body.handlebars
Fixes issue #123 
Changes: Add type of account when hovering on checked image
=> Show account type on result

lib/public/css/screen/base.css, package-lock.json, package.json, views/partials/body.handlebars
Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: [Add here what changes were made in this issue and if possible provide links.]
=> Animate toggle button with before psuedo and font awesome

lib/public/js/statements.js
Fixes issue #129 
Changes: Add a few sentences
=> Add supportive statements

README.md
=> Update docs in 2019

README.md
Documentation update for todo list
=> docs: update to do list in readme

package-lock.json, package.json
Add pre-commit hook for better visibility.
=> feat: add pre-commit hook

README.md
=> docs: update docs to accomodate new year goal

lib/public/js/chart.js, tests/utils/charts.test.js
Added unit test cases for `sum` and `slugify` functions inside `chart.js`.
=> Added unit tests for sum and slugify functions in chart.js

lib/public/css/base.scss
=> Change link color

.github/workflows/node.js.yml, README.md
=> doc: update readme content

public/js/chart.js
=> fix: fix issue of browing repo based on language

public/js/chart.js, src/api/controller.js, src/api/octokit.js, src/pages/partials/body.handlebars
=> Fix: differentiate browse repos based on user type

.env.example, README.md
=> doc(readme): update doc on how to generate and use classic token

gulpfile.js
- [x ] Other (remove dependency deprecation notice warning)
=> fix(lint): remove dangling comma

Dockerfile, docker-compose.yaml, package.json
=> ci: add dockerfile and docker-compose for local development

.github/workflows/deploy.yml
=> ci: add deploy to vps pipeline

src/api/routes.js, src/pages/partials/body.handlebars, src/pages/partials/copyright.handlebars, src/pages/partials/error.handlebars
- Add a link to the owner
- Extract out the copyright page
=> style: add color and link for the owner and refactor copyright.handlebars

src/api/controller.js
=> fix: pass current year to too many repos page handler

.github/workflows/deploy.yml
=> ci: add healthcheck before concluding deployment

src/pages/partials/body.handlebars
=> fix: add max username length of 39 chars

src/pages/partials/body.handlebars
=> style: remove link title

.github/workflows/deploy.yml, README.md
- update readme
- include test in deployment pipeline
=> doc: only refer to issues for feature tracker and bug report

.github/workflows/deploy.yml
=> ci: deploy to depend to test job

README.md, src/pages/partials/body.handlebars, src/pages/partials/head.handlebars
=> feat: change base URL for X and facebook

package-lock.json, package.json
=> chore: upgrade dep to the latest for axios

package-lock.json, package.json
=> chore: upgrade sass

package-lock.json, package.json
=> chore: upgrade lodash

package-lock.json, package.json
- remove `method-override` (unused anywhere)
- upgrade `body-parser`
=> chore: remove unused method-override and upgrade body-parser
